= Keycloak Site Reliability Engineers Special Interest Group (SRE SIG)

After an initial installation of Keycloak, users today spend a significant amount of time optimizing their installations, keeping them up to date and secure.
When doing this, they follow the principles of Site Reliability Engineers, among others automation, setting service level objectives, keeping things simple and monitoring.

The idea of this SIG is to speed up the feedback loop for existing and new features and to improve the communication between people operating Keycloak in real deployments and people developing Keycloak. Thanks to this collaboration, we can make Keycloak follow the SRE principles and make it easier to operate.

Desired outputs:

- Simplifying Keycloak’s configuration and upgrade process.
- Collecting best practices and feedback from real-world Keycloak installations to identify and prioritize new features.
- Educating users about what Keycloak can already do and what items are on the future roadmap.

== Current topics

See all topics that are currently on the radar of SIG in the following https://github.com/orgs/keycloak/projects/45[Github project].

=== Proposing a new topic

If you have a topic you would like to discuss with the group, please https://github.com/keycloak/keycloak-sre-sig/issues/new?labels=topic&template=topic-suggestion.yml[open a topic suggestion issue] in this repository.

== Meeting notes

The meeting notes are available at https://www.keycloak.org/keycloak-sre-sig/meetings/

== Communication channels

Besides this GitHub repository, we also use our https://cloud-native.slack.com/channels/keycloak-sre-sig[CNCF's #keycloak-sre-sig Slack channel] for more interactive discussions.
Use https://slack.cncf.io/ to join the CNCF slack if you don't have an account there.


